version: '3.8'

services:

  backend:
    container_name: backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure
    volumes:
      - ./core:/app
    env_file:
    - ./core/.env
    ports:
      - "8000:8000"
    networks:
      - main
    depends_on:
      - redis
  
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - main

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A core worker -l INFO --concurrency=3
    env_file:
      - ./core/.env
    depends_on:
      - redis
      - backend
    restart: unless-stopped
    networks:
      - main

volumes:
  redis_data:

networks:
  main: