[tool.ruff]

select = [
    "E",   
    "F",  
    "B",  
    "I",  
    "C",   
    "DJ", 
    "RET", 
    "PL",  
    "RUF",
    "SIM", 
    "TID",
    "ARG", 
    "ERA",
    "EM",  
    "PTH", 
]

ignore = [
    "B008", 
    "B904", 
    "E501",
]

line-length = 88
target-version = "py38"
exclude = [
    "migrations",
    "**/__pycache__",
    "**/.venv",
    "**/node_modules",
    "**/static",
    "**/media",
    "**/templates",
    "**/fixtures",
    "**/test_*.py",
    "**/tests.py",
]

[tool.ruff.dj]
model-admin-order = "alphabetical"
admin-model-registration = "explicit"

[tool.ruff.isort]
known-first-party = ["my_project", "my_app"]
required-imports = ["from __future__ import annotations"]
combine-as-imports = true
split-on-trailing-comma = true
order-by-type = true
force-sort-within-sections = true
lines-after-imports = 2

[tool.ruff.format]
quote-style = "double"
docstring-code-format = true
docstring-code-line-length = 72

[tool.ruff.per-file-ignores]
"*/migrations/*.py" = ["ALL"]
"*/admin.py" = ["DJ012"]  
"*/models.py" = ["DJ008"] 
"*/serializers.py" = ["DJ001", "DJ003"]
"*/views.py" = ["ARG001", "ARG002"]
"*/tests/*.py" = ["S101", "PT011", "PT018"]
"*/factories.py" = ["FBT001", "FBT002"]
"*/management/commands/*.py" = ["PLR0915"] 