# Generated by Django 5.2 on 2025-04-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.BigIntegerField(verbose_name='ID منبع')),
                ('date', models.DateField(verbose_name='تاریخ ثبت')),
                ('shareholder_id', models.BigIntegerField(verbose_name='شناسه سهامدار')),
                ('shareholder_shares', models.BigIntegerField(verbose_name='تعداد سهام')),
                ('shareholder_percentage', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='درصد سهام')),
                ('shareholder_instrument_id', models.CharField(max_length=20, verbose_name='شناسه ابزار مالی')),
                ('shareholder_name', models.CharField(max_length=255, verbose_name='نام سهامدار')),
                ('change', models.SmallIntegerField(verbose_name='تغییر')),
                ('symbol', models.CharField(max_length=50, verbose_name='نماد بورسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'سهامدار عمده',
                'verbose_name_plural': 'سهامداران عمده',
                'ordering': ['-date', '-shareholder_percentage'],
                'indexes': [models.Index(fields=['symbol'], name='shareholder_symbol_7b44ab_idx'), models.Index(fields=['date'], name='shareholder_date_e35a38_idx'), models.Index(fields=['shareholder_name'], name='shareholder_shareho_e2f9ac_idx')],
                'unique_together': {('original_id', 'date')},
            },
        ),
    ]
