# Generated by Django 4.2 on 2025-04-20 17:37

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareholdersHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='آیدی')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ ثبت میلادی')),
                ('shareholder_id', models.CharField(blank=True, max_length=55, null=True, verbose_name='شناسه سهامدار')),
                ('shareholder_shares', models.FloatField(blank=True, null=True, verbose_name='تعداد سهام')),
                ('shareholder_percentage', models.FloatField(blank=True, null=True, verbose_name='درصد سهام')),
                ('shareholder_instrument_id', models.CharField(blank=True, max_length=55, null=True, verbose_name='شناسه ابزار مالی')),
                ('shareholder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام سهامدار')),
                ('change', models.IntegerField(blank=True, null=True, verbose_name='تغییر')),
                ('symbol', models.CharField(blank=True, max_length=50, null=True, verbose_name='نماد بورسی')),
                ('jalali_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ثبت شمسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'سهامدار عمده',
                'verbose_name_plural': 'سهامداران عمده',
                'ordering': ['-date', '-shareholder_percentage'],
            },
        ),
        migrations.AddIndex(
            model_name='shareholdershistory',
            index=models.Index(fields=['symbol'], name='shareholder_symbol_2601af_idx'),
        ),
        migrations.AddIndex(
            model_name='shareholdershistory',
            index=models.Index(fields=['date'], name='shareholder_date_186f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='shareholdershistory',
            index=models.Index(fields=['shareholder_name'], name='shareholder_shareho_a42552_idx'),
        ),
    ]
