# Generated by Django 5.2 on 2025-04-12 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareholderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ محاسبه')),
                ('symbol', models.CharField(max_length=50, verbose_name='نماد بورسی')),
                ('shares', models.BigIntegerField(verbose_name='تعداد سهام')),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='درصد مالکیت')),
                ('shares_change', models.BigIntegerField(default=0, verbose_name='تغییر تعداد سهام')),
                ('percentage_change', models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='تغییر درصد مالکیت')),
                ('ownership_change_direction', models.CharField(choices=[('increase', 'افزایش'), ('decrease', 'کاهش'), ('stable', 'ثابت')], default='stable', max_length=10, verbose_name='جهت تغییر مالکیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='shareholder.shareholder', verbose_name='سهامدار')),
            ],
            options={
                'verbose_name': 'تاریخچه سهامدار',
                'verbose_name_plural': 'تاریخچه سهامداران',
                'ordering': ['-date', '-percentage'],
                'indexes': [models.Index(fields=['symbol'], name='shareholder_symbol_0ecf2a_idx'), models.Index(fields=['date'], name='shareholder_date_9c91ba_idx'), models.Index(fields=['shareholder'], name='shareholder_shareho_65bae6_idx')],
                'unique_together': {('shareholder', 'date')},
            },
        ),
    ]
